Fix BLE connection (#907)
## :recycle: Current situation
The `require` function is not supported with ESM, leading the following
error:
```
ReferenceError: require is not defined
```

## :bulb: Proposed solution

Use a dynamic import.